export const algorithms = {
  quickSort: {
    id: 'quickSort',
    name: 'Quick Sort',
    category: 'Sorting',
    description: 'Sort an array using the divide-and-conquer quick sort algorithm',
    explanation: 'Quick Sort is a highly efficient, divide-and-conquer sorting algorithm. It works by selecting a "pivot" element and partitioning the array so that elements smaller than the pivot are on the left, and larger elements are on the right. This partitioning is applied recursively to sort the sub-arrays in O(N log N) average time complexity.',
    defaultInput: [5,2,9,1,5,6],
    simulate: (arr) => import('./sorting/quickSort/simulate').then(m => m.simulateQuickSort(arr)),
    code: [
      "function quickSort(arr, low, high) {",
      "  if (low < high) {",
      "    let pi = partition(arr, low, high);",
      "    quickSort(arr, low, pi - 1);",
      "    quickSort(arr, pi + 1, high);",
      "  }",
      "}",
      "function partition(arr, low, high) {",
      "  let pivot = arr[high];",
      "  let i = low - 1;",
      "  for (let j = low; j < high; j++) {",
      "    if (arr[j] < pivot) {",
      "      i++;",
      "      [arr[i], arr[j]] = [arr[j], arr[i]];",
      "    }",
      "  }",
      "  [arr[i + 1], arr[high]] = [arr[high], arr[i + 1]];",
      "  return i + 1;",
      "}"
    ].join('\n')
  },
  mergeSort: {
    id: 'mergeSort',
    name: 'Merge Sort',
    category: 'Sorting',
    description: 'Sort an array by dividing it into halves and merging them',
    explanation: 'Merge Sort is a stable, divide-and-conquer algorithm. It recursively divides the array into two halves until each sub-array contains a single element. Then, it repeatedly merges the sub-arrays back together in sorted order, guaranteeing an O(N log N) time complexity in all cases.',
    defaultInput: [38, 27, 43, 3, 9, 82, 10],
    simulate: (arr) => import('./sorting/mergeSort/simulate').then(m => m.simulateMergeSort(arr)),
    code: [
      "function mergeSort(arr, l, r) {",
      "  if (l >= r) return;",
      "  let m = l + Math.floor((r - l) / 2);",
      "  mergeSort(arr, l, m);",
      "  mergeSort(arr, m + 1, r);",
      "  merge(arr, l, m, r);",
      "}",
      "function merge(arr, l, m, r) {",
      "  let n1 = m - l + 1, n2 = r - m;",
      "  let L = new Array(n1), R = new Array(n2);",
      "  for (let i = 0; i < n1; i++) L[i] = arr[l + i];",
      "  for (let j = 0; j < n2; j++) R[j] = arr[m + 1 + j];",
      "  let i = 0, j = 0, k = l;",
      "  while (i < n1 && j < n2) {",
      "    if (L[i] <= R[j]) { arr[k] = L[i]; i++; }",
      "    else { arr[k] = R[j]; j++; }",
      "    k++;",
      "  }",
      "  while (i < n1) { arr[k] = L[i]; i++; k++; }",
      "  while (j < n2) { arr[k] = R[j]; j++; k++; }",
      "}"
    ].join('\n')
  },
  dutch: {
    id: 'dutch',
    name: 'Dutch National Flag',
    category: 'Sorting',
    description: 'Sort an array of 0s, 1s, and 2s',
    explanation: 'The Dutch National Flag algorithm partitions an array of items into three groups (0s, 1s, and 2s) in a single pass. Using three pointers (low, mid, high), it places 0s on the left and 2s on the right in O(N) linear time.',
    defaultInput: [2,0,2,1,1,0],
    simulate: (arr) => import('./dutch/simulate').then(m => m.simulateDutch(arr)),
    code: [
      "function sortColors(nums) {",
      "  let low = 0, mid = 0, high = nums.length - 1;",
      "  while (mid <= high) {",
      "    if (nums[mid] === 0) {",
      "      [nums[low], nums[mid]] = [nums[mid], nums[low]];",
      "      low++; mid++;",
      "    } else if (nums[mid] === 1) {",
      "      mid++;",
      "    } else {",
      "      [nums[mid], nums[high]] = [nums[high], nums[mid]];",
      "      high--;",
      "    }",
      "  }",
      "}"
    ].join('\n')
  },
  cycle: {
    id: 'cycle',
    name: 'Detect Cycle II',
    category: 'Linked List',
    description: "Floyd's cycle detection algorithm",
    explanation: "Floyd's Cycle Detection uses a slow pointer (1 step) and a fast pointer (2 steps). If the list contains a cycle, the pointers will meet. Then a third pointer from the head pinpoints the exact cycle start node in O(N) time.",
    defaultInput: [1,2,3,4,5,6,7],
    simulate: (config) => import('./floyd/simulate').then(m => m.simulateFloyd(config)),
    code: [
      "function detectCycle(head) {",
      "  let slow = head; let fast = head;",
      "  while (fast && fast.next) {",
      "    slow = slow.next;",
      "    fast = fast.next.next;",
      "    if (slow === fast) break;",
      "  }",
      "  if (!fast || !fast.next) return null;",
      "  slow = head;",
      "  while (slow !== fast) {",
      "    slow = slow.next;",
      "    fast = fast.next;",
      "  }",
      "  return slow;",
      "}"
    ].join('\n')
  },
  perfectSquares: {
    id: 'perfectSquares',
    name: 'Minimum Perfect Squares',
    category: 'Dynamic Programming',
    description: 'Find the least number of perfect squares that sum to n',
    explanation: 'This DP algorithm finds the minimum number of perfect square numbers (1, 4, 9, 16, ...) that sum to a given integer n. It builds a dp array where dp[i] stores the minimum squares needed for value i, running in O(n√n) time.',
    defaultInput: [12],
    simulate: (inputStr) => import('./perfectSquares/simulate').then(m => m.simulatePerfectSquares(inputStr)),
    code: [
      "function numSquares(n) {",
      "  let dp = new Array(n+1).fill(Infinity);",
      "  dp[0] = 0;",
      "  for (let i = 1; i <= n; i++) {",
      "    for (let j = 1; j*j <= i; j++) {",
      "      dp[i] = Math.min(dp[i], dp[i - j*j] + 1);",
      "    }",
      "  }",
      "  return dp[n];",
      "}"
    ].join('\n')
  },
  subsequences: {
    id: 'subsequences',
    name: 'Get Subsequences',
    category: 'Recursion',
    description: 'Generate all subsequences of a string',
    explanation: 'This backtracking algorithm generates all possible subsequences of a string by making two choices at each character: include it or exclude it. This produces 2^n total subsequences.',
    defaultInput: ['abc'],
    simulate: (inputStr) => import('./subsequences/simulate').then(m => m.simulateSubsequences(inputStr)),
    code: [
      "function getSubsequences(str, index = 0, current = '', result = []) {",
      "  if (index === str.length) {",
      "    result.push(current);",
      "    return;",
      "  }",
      "  ",
      "  // exclude current char",
      "  getSubsequences(str, index + 1, current, result);",
      "  ",
      "  // include current char",
      "  getSubsequences(str, index + 1, current + str[index], result);",
      "  ",
      "  return result;",
      "}"
    ].join('\n')
  },
  lis: {
    id: 'lis',
    name: 'Longest Increasing Subsequence',
    category: 'Dynamic Programming',
    description: 'Find the length of the longest strictly increasing subsequence',
    explanation: 'The LIS algorithm uses dynamic programming where dp[i] represents the length of the longest increasing subsequence ending at index i. For each element, it checks all previous elements to find valid extensions. Runs in O(N²) time.',
    defaultInput: [10,9,2,5,3,7,101,18],
    simulate: (arr) => import('./dp/lis/simulate').then(m => m.simulateLIS(arr)),
    code: [
      "function lengthOfLIS(nums) {",
      "  let dp = new Array(nums.length).fill(1);",
      "  for (let i = 0; i < nums.length; i++) {",
      "    for (let j = 0; j < i; j++) {",
      "      if (nums[i] > nums[j]) {",
      "        dp[i] = Math.max(dp[i], dp[j] + 1);",
      "      }",
      "    }",
      "  }",
      "  return Math.max(...dp);",
      "}"
    ].join('\n')
  },
  permutations: {
    id: 'permutations',
    name: 'Permutations',
    category: 'Recursion',
    description: 'Generate all permutations of an array using backtracking',
    explanation: 'This algorithm generates all permutations by swapping each element into the current position and recursively permuting the remaining elements. It produces n! total permutations.',
    defaultInput: [1, 2, 3],
    simulate: (arr) => import('./recursion/permutations/simulate').then(m => m.simulatePermutations(arr)),
    code: [
      "function permute(nums) {",
      "  let result = [];",
      "  function backtrack(start) {",
      "    if (start === nums.length) {",
      "      result.push([...nums]);",
      "      return;",
      "    }",
      "    for (let i = start; i < nums.length; i++) {",
      "      [nums[start], nums[i]] = [nums[i], nums[start]];",
      "      backtrack(start + 1);",
      "      [nums[start], nums[i]] = [nums[i], nums[start]];",
      "    }",
      "  }",
      "  backtrack(0);",
      "  return result;",
      "}"
    ].join('\n')
  },
  subsets: {
    id: 'subsets',
    name: 'Subsets',
    category: 'Recursion',
    description: 'Generate all subsets of an array using backtracking',
    explanation: 'This algorithm generates all 2^n subsets by iterating through each element and choosing to include or skip it, building subsets incrementally via backtracking.',
    defaultInput: [1, 2, 3],
    simulate: (inputStr) => import('./recursion/subsets/simulate').then(m => m.simulateSubsets(inputStr)),
    code: [
      "function subsets(nums) {",
      "  let result = [];",
      "  function backtrack(index, current) {",
      "    result.push([...current]);",
      "    for (let i = index; i < nums.length; i++) {",
      "      current.push(nums[i]);",
      "      backtrack(i + 1, current);",
      "      current.pop();",
      "    }",
      "  }",
      "  backtrack(0, []);",
      "  return result;",
      "}"
    ].join('\n')
  },
  palindromeList: {
    id: 'palindromeList',
    name: 'Palindrome Linked List',
    category: 'Linked List',
    description: 'Determine whether a singly linked list is a palindrome',
    explanation: 'This algorithm uses the fast/slow pointer technique to find the middle, reverses the second half, then compares both halves node by node. Runs in O(N) time with O(1) extra space.',
    defaultInput: '1,2,3,2,1',
    simulate: (str) => import('./linkedList/palindrome/simulate').then(m => m.simulatePalindromeList(str)),
    code: [
      "function isPalindrome(head) {",
      "  if (!head) return true;",
      "  let slow = head, fast = head;",
      "  while (fast && fast.next) {",
      "    slow = slow.next;",
      "    fast = fast.next.next;",
      "  }",
      "  let prev = null, curr = slow;",
      "  while (curr) {",
      "    let next = curr.next;",
      "    curr.next = prev;",
      "    prev = curr;",
      "    curr = next;",
      "  }",
      "  let left = head, right = prev;",
      "  while (right) {",
      "    if (left.val !== right.val) return false;",
      "    left = left.next;",
      "    right = right.next;",
      "  }",
      "  return true;",
      "}"
    ].join('\n')
  }
};
